services:
  db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - trello-copy-db-data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - trello-copy-redis-data:/data

volumes:
  trello-copy-db-data:
    driver: local
  trello-copy-redis-data:
    driver: local
